/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/    @Override
    public void propertyChange(PropertyChangeEvent evt)     @Override
    public void propertyChange(PropertyChangeEvent evt) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
{
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import Utilidades.UtilidadesFechas;
import com.sun.corba.se.spi.orb.OperationFactory;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.temporal.ChronoUnit;
import java.util.Date;
import java.util.concurrent.TimeUnit;
import javax.swing.JOptionPane;

/**
 *
 * @author Victor
 */
public class InterfazFecha extends javax.swing.JFrame {

    /**
     * Creates new form InterfazFecha
     */
    public InterfazFecha() {
        initComponents();
        this.setLocationRelativeTo(null);
        MostrarFechaHoy();
    }

    public void MostrarFechaHoy() {
        lblFechaActualMostrar.setText(UtilidadesFechas.fechaHoy());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFechaIngreso = new javax.swing.JPanel();
        lblIngresarFecha = new javax.swing.JLabel();
        btnAceptarFecha = new javax.swing.JButton();
        btnSalirFecha = new javax.swing.JButton();
        lblFechaSeleccionada = new javax.swing.JLabel();
        lblFechaSeleccionadaMostrar = new javax.swing.JLabel();
        lblFechaActualTitulo = new javax.swing.JLabel();
        lblFechaActualMostrar = new javax.swing.JLabel();
        btnRegistrarFechaSeleccionada = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblTiempoTrabajo = new javax.swing.JLabel();
        chIngresarFecha = new com.toedter.calendar.JDateChooser();
        btnCargarTiempoTranajo = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("INGRESAR FECHA");

        panelFechaIngreso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblIngresarFecha.setText("FECHA DE INGRESO A TRABAJAR");

        btnAceptarFecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/AceptarIconoFinal.png"))); // NOI18N
        btnAceptarFecha.setText("ACEPTAR");
        btnAceptarFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarFechaActionPerformed(evt);
            }
        });

        btnSalirFecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/SalirIconoFinal.png"))); // NOI18N
        btnSalirFecha.setText("SALIR");
        btnSalirFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirFechaActionPerformed(evt);
            }
        });

        lblFechaSeleccionada.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFechaSeleccionada.setText("Fecha seleccionada");

        lblFechaSeleccionadaMostrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblFechaActualTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFechaActualTitulo.setText("Fecha actual");

        lblFechaActualMostrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnRegistrarFechaSeleccionada.setText("REGISTRAR FECHA");
        btnRegistrarFechaSeleccionada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarFechaSeleccionadaActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tiempo de Trabajo");

        lblTiempoTrabajo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTiempoTrabajo.setText(".");

        btnCargarTiempoTranajo.setText("CALCULAR TIEMPO DE TRABAJO");
        btnCargarTiempoTranajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarTiempoTranajoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelFechaIngresoLayout = new javax.swing.GroupLayout(panelFechaIngreso);
        panelFechaIngreso.setLayout(panelFechaIngresoLayout);
        panelFechaIngresoLayout.setHorizontalGroup(
            panelFechaIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFechaIngresoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panelFechaIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblIngresarFecha)
                    .addComponent(btnAceptarFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSalirFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCargarTiempoTranajo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblFechaActualMostrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTiempoTrabajo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblFechaActualTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblFechaSeleccionadaMostrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblFechaSeleccionada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRegistrarFechaSeleccionada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chIngresarFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );
        panelFechaIngresoLayout.setVerticalGroup(
            panelFechaIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFechaIngresoLayout.createSequentialGroup()
                .addComponent(lblIngresarFecha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chIngresarFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegistrarFechaSeleccionada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFechaSeleccionada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFechaSeleccionadaMostrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFechaActualTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFechaActualMostrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTiempoTrabajo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCargarTiempoTranajo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAceptarFecha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalirFecha)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelFechaIngreso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelFechaIngreso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirFechaActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirFechaActionPerformed

    private void btnAceptarFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarFechaActionPerformed
        if (lblFechaSeleccionadaMostrar.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "NO SE HA REGISTRADO LA FECHA", "EROOR", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "La fecha seleccionada es " + lblFechaSeleccionadaMostrar.getText());

            InterfazPresentacion.lblFechaIngreso.setText(lblFechaSeleccionadaMostrar.getText());
            this.dispose();
        }

//        InterfazPresentacion presentacionInterfaz = new InterfazPresentacion();
//        presentacionInterfaz.setDato(lblFechaSeleccionadaMostrar.getText());
//        this.dispose();
//        presentacionInterfaz.setVisible(true);
//        InterfazPresentacion abrir = new InterfazPresentacion();
//        abrir.setVisible(true);
//        
//        this.dispose();
    }//GEN-LAST:event_btnAceptarFechaActionPerformed
    private void btnRegistrarFechaSeleccionadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarFechaSeleccionadaActionPerformed
        // TODO add your handling code here:
        if (chIngresarFecha.getDate() == null) {
            JOptionPane.showMessageDialog(null, "NO SE HA SELECCIONADO LA FECHA", "EROOR", JOptionPane.INFORMATION_MESSAGE);
        } else {
            lblFechaSeleccionadaMostrar.setText(UtilidadesFechas.fechaSeleccionada());
//            btnRegistrarFechaSeleccionada.setEnabled(false);
//            lblTiempoTrabajo.setText(UtilidadesFechas.TiempoCalcular());
            
        }
        if(lblFechaSeleccionadaMostrar.getText().isEmpty()){
        }else{
            btnRegistrarFechaSeleccionada.setEnabled(false);
        }
//        btnRegistrarFechaSeleccionada.setEnabled(false);
    }//GEN-LAST:event_btnRegistrarFechaSeleccionadaActionPerformed

    private void btnCargarTiempoTranajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarTiempoTranajoActionPerformed
        // TODO add your handling code here:
        lblTiempoTrabajo.setText(UtilidadesFechas.calculoFecha());

//        String dateBeforeString = lblFechaSeleccionadaMostrar.getText();
//	String dateAfterString = lblFechaActualMostrar.getText();
//		
//	LocalDate dateBefore = LocalDate.parse(dateBeforeString);
//	LocalDate dateAfter = LocalDate.parse(dateAfterString);
//		
//	//calculating number of days in between
//        short noOfYearBetween = (short) ChronoUnit.YEARS.between(dateBefore, dateAfter);
//		
//	//displaying the number of days
//	System.out.println(+noOfYearBetween);
//        
//        LocalDate dateBefore = LocalDate.parse(dateBeforeString);
//        LocalDate dateAfter = LocalDate.parse(dateAfterString);
//        
//        long noOfDayBetween = ChronoUnit.DAYS.between(dateBefore, dateAfter);
//        
//        System.out.println(noOfDayBetween);

//        String FechaHoy = new SimpleDateFormat("dd/MM/YYYY").format(Date.parse(lblFechaActualMostrar));
//        String FechaSeleccionada = new SimpleDateFormat("dd/MM/YYYY").format(lblFechaSeleccionadaMostrar);
//        String[] dateParts = FechaHoy.split("/");
//        String dia = dateParts[0],
//                mes = dateParts[1],
//                año = dateParts[3];
//        String[] datePartsSelecionado = FechaSeleccionada.split("/");
//        String diaSelect = datePartsSelecionado[0],
//                mesSelect = datePartsSelecionado[1],
//                añoSelect = datePartsSelecionado[2];
//        
//        String año_actual = UtilidadesFechas.fechaHoy();
//        String año_selecionado = UtilidadesFechas.fechaSeleccionada();
//        
//        int edad;
//        
//        edad = Integer.parseInt(año_actual) - Integer.parseInt(añoSelect);
//        
//        lblTiempoTrabajo.setText(""+edad);
    }//GEN-LAST:event_btnCargarTiempoTranajoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazFecha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazFecha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazFecha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazFecha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazFecha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptarFecha;
    private javax.swing.JToggleButton btnCargarTiempoTranajo;
    private javax.swing.JButton btnRegistrarFechaSeleccionada;
    private javax.swing.JButton btnSalirFecha;
    public static com.toedter.calendar.JDateChooser chIngresarFecha;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel lblFechaActualMostrar;
    private javax.swing.JLabel lblFechaActualTitulo;
    private javax.swing.JLabel lblFechaSeleccionada;
    public static javax.swing.JLabel lblFechaSeleccionadaMostrar;
    private javax.swing.JLabel lblIngresarFecha;
    public static javax.swing.JLabel lblTiempoTrabajo;
    private javax.swing.JPanel panelFechaIngreso;
    // End of variables declaration//GEN-END:variables
}
