/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/    @Override
    public void propertyChange(PropertyChangeEvent evt)     @Override
    public void propertyChange(PropertyChangeEvent evt) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
{
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import Utilidades.UtilidadesFechas;
import com.sun.corba.se.spi.orb.OperationFactory;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.temporal.ChronoUnit;
import java.util.Date;
import java.util.concurrent.TimeUnit;
import javax.swing.JOptionPane;

/**
 *
 * @author Victor
 */
public class InterfazFecha extends javax.swing.JFrame {

    /**
     * Creates new form InterfazFecha
     */
    public InterfazFecha() {
        initComponents();
        this.setLocationRelativeTo(null);
        MostrarFechaHoy();
    }

    public void MostrarFechaHoy() {
        lblFechaActualMostrar.setText(UtilidadesFechas.fechaHoy());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFechaIngreso = new javax.swing.JPanel();
        btnAceptarFecha = new javax.swing.JButton();
        btnSalirFecha = new javax.swing.JButton();
        lblFechaSeleccionada = new javax.swing.JLabel();
        lblFechaSeleccionadaMostrar = new javax.swing.JLabel();
        lblFechaActualTitulo = new javax.swing.JLabel();
        lblFechaActualMostrar = new javax.swing.JLabel();
        btnRegistrarFechaSeleccionada = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblTiempoTrabajo = new javax.swing.JLabel();
        chIngresarFecha = new com.toedter.calendar.JDateChooser();
        btnCargarTiempoTranajo = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("INGRESAR FECHA");

        panelFechaIngreso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelFechaIngreso.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAceptarFecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/AceptarIconoFinal.png"))); // NOI18N
        btnAceptarFecha.setText("ACEPTAR");
        btnAceptarFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarFechaActionPerformed(evt);
            }
        });
        panelFechaIngreso.add(btnAceptarFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 560, 130, -1));

        btnSalirFecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/SalirIconoFinal.png"))); // NOI18N
        btnSalirFecha.setText("SALIR");
        btnSalirFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirFechaActionPerformed(evt);
            }
        });
        panelFechaIngreso.add(btnSalirFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, 140, -1));

        lblFechaSeleccionada.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblFechaSeleccionada.setForeground(new java.awt.Color(255, 0, 0));
        lblFechaSeleccionada.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFechaSeleccionada.setText("Fecha seleccionada");
        panelFechaIngreso.add(lblFechaSeleccionada, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 160, -1));

        lblFechaSeleccionadaMostrar.setForeground(new java.awt.Color(255, 255, 255));
        lblFechaSeleccionadaMostrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelFechaIngreso.add(lblFechaSeleccionadaMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 210, 20));

        lblFechaActualTitulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblFechaActualTitulo.setForeground(new java.awt.Color(255, 0, 0));
        lblFechaActualTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFechaActualTitulo.setText("Fecha actual");
        panelFechaIngreso.add(lblFechaActualTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 170, -1));

        lblFechaActualMostrar.setForeground(new java.awt.Color(255, 255, 255));
        lblFechaActualMostrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelFechaIngreso.add(lblFechaActualMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 203, 20));

        btnRegistrarFechaSeleccionada.setText("REGISTRAR FECHA");
        btnRegistrarFechaSeleccionada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarFechaSeleccionadaActionPerformed(evt);
            }
        });
        panelFechaIngreso.add(btnRegistrarFechaSeleccionada, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 150, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tiempo de Trabajo");
        panelFechaIngreso.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, 160, -1));

        lblTiempoTrabajo.setForeground(new java.awt.Color(255, 255, 255));
        lblTiempoTrabajo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTiempoTrabajo.setText(".");
        panelFechaIngreso.add(lblTiempoTrabajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 450, 140, 20));

        chIngresarFecha.setDateFormatString("dd MM yyyy");
        panelFechaIngreso.add(chIngresarFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 210, -1));

        btnCargarTiempoTranajo.setText("CALCULAR TIEMPO DE TRABAJO");
        btnCargarTiempoTranajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarTiempoTranajoActionPerformed(evt);
            }
        });
        panelFechaIngreso.add(btnCargarTiempoTranajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 490, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("INGRESAR FECHA DE TRABAJO");
        panelFechaIngreso.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FONDOS/FondoCalendario.jpg"))); // NOI18N
        panelFechaIngreso.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 380, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFechaIngreso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 356, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFechaIngreso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirFechaActionPerformed
        // TODO add your handling code here:
        this.dispose();
//        System.exit(0);
    }//GEN-LAST:event_btnSalirFechaActionPerformed

    private void btnAceptarFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarFechaActionPerformed
        if (lblFechaSeleccionadaMostrar.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "NO SE HA REGISTRADO LA FECHA", "EROOR", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "La fecha seleccionada es " + lblFechaSeleccionadaMostrar.getText());

            InterfazPresentacion.lblFechaIngreso.setText(lblFechaSeleccionadaMostrar.getText());
            this.dispose();
        }

//        InterfazPresentacion presentacionInterfaz = new InterfazPresentacion();
//        presentacionInterfaz.setDato(lblFechaSeleccionadaMostrar.getText());
//        this.dispose();
//        presentacionInterfaz.setVisible(true);
//        InterfazPresentacion abrir = new InterfazPresentacion();
//        abrir.setVisible(true);
//        
//        this.dispose();
    }//GEN-LAST:event_btnAceptarFechaActionPerformed
    private void btnRegistrarFechaSeleccionadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarFechaSeleccionadaActionPerformed
        // TODO add your handling code here:
        if (chIngresarFecha.getDate() == null) {
            JOptionPane.showMessageDialog(null, "NO SE HA SELECCIONADO LA FECHA", "EROOR", JOptionPane.INFORMATION_MESSAGE);
        } else {
            lblFechaSeleccionadaMostrar.setText(UtilidadesFechas.fechaSeleccionada());
//            btnRegistrarFechaSeleccionada.setEnabled(false);
//            lblTiempoTrabajo.setText(UtilidadesFechas.TiempoCalcular());
            
        }
        if(lblFechaSeleccionadaMostrar.getText().isEmpty()){
        }else{
            btnRegistrarFechaSeleccionada.setEnabled(false);
        }
//        btnRegistrarFechaSeleccionada.setEnabled(false);
    }//GEN-LAST:event_btnRegistrarFechaSeleccionadaActionPerformed

    private void btnCargarTiempoTranajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarTiempoTranajoActionPerformed
        // TODO add your handling code here:
//        short FechaInicio, FechaSelecionada,ResultadoFecha;
//        
//        FechaInicio = (short) Date.parse(lblFechaActualMostrar.getText().toString());
//        FechaSelecionada = (short) Date.parse(lblFechaSeleccionadaMostrar.getText().toString());
//        
//        ResultadoFecha = (short) (FechaInicio - FechaSelecionada);
//        
//        lblTiempoTrabajo.setText(""+ResultadoFecha);
//        lblTiempoTrabajo.setText(UtilidadesFechas.calculoFecha());
        
        
//        lblTiempoTrabajo.setText(UtilidadesFechas.calculoFecha());

    }//GEN-LAST:event_btnCargarTiempoTranajoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazFecha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazFecha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazFecha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazFecha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazFecha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptarFecha;
    private javax.swing.JToggleButton btnCargarTiempoTranajo;
    private javax.swing.JButton btnRegistrarFechaSeleccionada;
    private javax.swing.JButton btnSalirFecha;
    public static com.toedter.calendar.JDateChooser chIngresarFecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public static javax.swing.JLabel lblFechaActualMostrar;
    private javax.swing.JLabel lblFechaActualTitulo;
    private javax.swing.JLabel lblFechaSeleccionada;
    public static javax.swing.JLabel lblFechaSeleccionadaMostrar;
    public static javax.swing.JLabel lblTiempoTrabajo;
    private javax.swing.JPanel panelFechaIngreso;
    // End of variables declaration//GEN-END:variables
}
